pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }


        stage('Create Folder') {
            steps {
                script {
                    def folderPath = '/'  // Specify the folder path
                    def folderName = 'target/my-app'             // Specify the folder name
                    def folder = new File(folderPath, folderName)
                    
                    if (!folder.exists()) {
                        folder.mkdirs()
                        echo "Folder '${folderName}' created successfully."
                    } else {
                        echo "Folder '${folderName}' already exists."
                    }
                }
            }
        }
        
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
