pipeline {
    agent any
    environment{
        PATH="$PATH:/tmp/apache-maven-3.9.4/bin"
    }
    stages {
        stage("Clone"){
            steps{
                sh """
                git clone https://github.com/khandakerislam/simple-java-maven-app
                """
            }
        }
        stage('Build') {
            steps {
                sh """
                ls
                cd simple-java-maven-app
                mvn -B -DskipTests clean package
                """
            }
        }
        stage('Test') {
            steps {
                sh """
                cd simple-java-maven-app
                mvn test
                """
            }
        }
        stage('Deliver') {
            steps {
                sh """
                cd simple-java-maven-app
                mv target/my-app-1.0-SNAPSHOT.jar target/my-app-123.jar
                ./jenkins/scripts/deliver.sh
                """
            }
        }
        stage('Complete') {
            steps {
                print "Job complete"
            }
            post {
                always {
                    junit 'simple-java-maven-app/target/surefire-reports/*.xml'
                    cleanWs()
                }
            }
        }
    }
}
